os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - home="$(pwd)"
  - travis_dir="${home}/images/${VERSION}/${VARIANT}"

install:
  - cd "$travis_dir"
  # Test containers build
  - travis_retry docker-compose build

before_script:
  - docker images

script:
  - cd "$travis_dir"
  # Test containers run
  - docker-compose up -d && sleep 60
  - docker-compose ps
  #- docker-compose logs
  - docker-compose logs "taiga_back"
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose logs "taiga_celery"
  - docker-compose ps "taiga_celery" | grep "Up"
  - docker-compose logs "taiga_front"
  - docker-compose ps "taiga_front" | grep "Up"
  # TODO Test Front custom setup properly applied
  #- curl http://localhost:80/config.json
  #- curl http://localhost:80/config.json | grep 'gitlab-auth.json'
  #- curl http://localhost:80/config.json | grep 'github-auth.json'
  #- curl http://localhost:80/config.json | grep '"ldap"'
  # Test containers can be dropped and restarted
  - docker-compose down
  - docker-compose up -d && sleep 60
  - docker-compose ps
  #- docker-compose logs
  - docker-compose logs "taiga_back"
  - docker-compose ps "taiga_back" | grep "Up"
  - docker-compose logs "taiga_celery"
  - docker-compose ps "taiga_celery" | grep "Up"
  - docker-compose logs "taiga_front"
  - docker-compose ps "taiga_front" | grep "Up"

after_script:
  - docker ps -a

notifications:
  email: false

env: # Environments
    - VERSION=4.0 VARIANT=alpine
    - VERSION=4.1 VARIANT=alpine
    - VERSION=4.2 VARIANT=alpine
    - VERSION=5.0 VARIANT=alpine
